import { chromium } from '@playwright/test';
process.env.PLAYWRIGHT_BROWSERS_PATH ??= '/opt/pw-browsers';
const OUT='/tmp/claude-0/-home-user-260914/fa042630-0978-56be-9ddd-9330ae7d5132/scratchpad/shots';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('pageerror', e => console.log('PAGEERROR', e));
await p.goto('http://127.0.0.1:4173/');
await p.waitForFunction(() => window.__kids?.ready === true);
await p.waitForTimeout(1000);
await p.mouse.move(195,600); await p.mouse.down();
await p.waitForTimeout(80);
await p.screenshot({ path: `${OUT}/g-ring.png` });
await p.mouse.up();
await p.evaluate(() => window.__kids.autoAdvance());
await p.waitForFunction(() => window.__kids.scenePhase() === 'clapping', undefined, {timeout: 40000});
await p.waitForTimeout(350);
await p.screenshot({ path: `${OUT}/g-clap.png` });
await b.close();
